\documentclass[9pt,twocolumn,twoside,]{pnas-new}

%% Some pieces required from the pandoc template
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Use the lineno option to display guide line numbers if required.
% Note that the use of elements such as single-column equations
% may affect the guide line number alignment.


\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage{longtable}

<<params, echo=FALSE, message=FALSE, comment=FALSE, results=hide>>=
params <- list(databaseId = "MDCR",
               targetId = 715259,
               comparatorId = 739138,
               outcomeId = 18,
               primary = 2,
               ot = 1,
               itt = 2,
               indication = tolower("major depressive disorder"),
               databaseName = "Truven MarketScan Multi-State Medicaid")
@

<<setup, echo=FALSE, message=FALSE, comment=FALSE, results=hide>>=
library(DatabaseConnector)
library(CohortMethod)
library(Legend)
library(knitr)
library(xtable)
library(ggplot2)
source("DataPulls.R")
source("PlotsAndTables.R")
options(knitr.kable.NA = '')

useStoredObject <- TRUE

if (!useStoredObject) {
    connectionDetails <- createConnectionDetails(dbms = "postgresql",
                                                 server = "localhost/ohdsi",
                                                 user = "postgres",
                                                 password = Sys.getenv("pwPostgres"),
                                                 schema = "legend")
    connection <- connect(connectionDetails)
    targetName <- tolower(getExposureName(connection, params$targetId))
    comparatorName <- tolower(getExposureName(connection, params$comparatorId))
    outcomeName <- tolower(getOutcomeName(connection, params$outcomeId))
    analyses <- getAnalyses(connection)
    mainResults <- getMainResults(connection,
                                  targetIds = params$targetId,
                                  comparatorIds = params$comparatorId,
                                  outcomeIds = params$outcomeId,
                                  databaseIds = params$databaseId)

    attrition <- getAttrition(connection,
                              targetId = params$targetId,
                              comparatorId = params$comparatorId,
                              outcomeId = params$outcomeId,
                              analysisId = 1,
                              databaseId = params$databaseId)

    balance <- getCovariateBalance(connection,
                                   targetId = params$targetId,
                                   comparatorId = params$comparatorId,
                                   databaseId = params$databaseId)

    ps <- getPs(connection,
                targetId = params$targetId,
                comparatorId = params$comparatorId,
                databaseId = params$databaseId)

    kaplanMeier <- getKaplanMeier(connection,
                                  targetId = params$targetId,
                                  comparatorId = params$comparatorId,
                                  outcomeId = params$outcomeId,
                                  databaseId = params$databaseId,
                                  analysisId = 2)
} else {
    load("paperData.rda")
    targetName <- tolower(targetName)
    comparatorName <- tolower(comparatorName)
    outcomeName <- tolower(outcomeName)  
}
@

\templatetype{pnasresearcharticle}  % Choose template

\title{ \Sexpr{capitalize(outcomeName)} risk in new-users of \Sexpr{targetName} versus \Sexpr{comparatorName}
for \Sexpr{params$indication} in the \Sexpr{params$databaseId} database}

\author[a,b,c,1]{Martijn J. Schuemie}
\author[a,b,d]{Patrick B. Ryan}
\author[a,e]{Seng Chan You}
\author[a,f]{Nicole Pratt}
\author[a,g]{David Madigan}
\author[a,d]{George Hripcsak}
\author[a,c,h,i]{Marc A. Suchard}

  \affil[a]{Observational Health Data Sciences and Informatics, New York, NY, USA}
  \affil[b]{Janssen Research \& Development, Titusville, NJ, USA}
  \affil[c]{Department of Biostatistics, University of Califoria, Los Angeles, CA}
  \affil[d]{Department of Biomedical Informatics, Columbia University, New York, NY}
  \affil[e]{Department of Biomedical Informatics, Ajou University, Suwon, South
Korea}
  \affil[f]{Sansom Institute, University of South Australia, Adelaide SA, Australia}
  \affil[g]{Department of Statistics, Columbia University, New York, NY}
  \affil[h]{Department of Biomathematics, University of Califoria, Los Angeles, CA}
  \affil[i]{Department of Human Genetics, University of Califoria, Los Angeles, CA}


% Please give the surname of the lead author for the running footer
\leadauthor{Schuemie}

% Please add here a significance statement to explain the relevance of your work
% \significancestatement{Authors must submit a 120-word maximum statement about the significance
% of their research paper written at a level understandable to an
% undergraduate educated scientist outside their field of speciality. The
% primary goal of the Significance Statement is to explain the relevance
% of the work in broad context to a broad readership. The Significance
% Statement appears in the paper itself and is required for all research
% papers.}

% \authorcontributions{Please provide details of author contributions here.}

\authordeclaration{
MJS and PBR are employees and share-holders of Janssen Research.
MAS receives contract support from Janssen Research.
}

\equalauthors{\textsuperscript{} }

\correspondingauthor{\textsuperscript{Corresponding author contact: \url{mschuemie@ohdsi.org}} }

% Keywords are not mandatory, but authors are strongly encouraged to provide them. If provided, please include two to five keywords, separated by the pipe symbol, e.g:
 % \keywords{  one |  two |  optional |  optional |  optional   }

\begin{abstract}
We conduct a large-scale study on the incidence of \Sexpr{outcomeName} among new users of \Sexpr{targetName} and \Sexpr{comparatorName} from XXXX to XXXX in the \Sexpr{params$databaseId} database.
The primary outcome of interest is an estimate of the hazard ratio (HR) for incident events between comparable new users under an intent-to-treat risk window assumption. Secondary analyses consider an on-treatment risk window assumption and entertain possible clinically relevant subgroup interaction with the HR.
We identify \Sexpr{mainResults[params$primary,"targetSubjects"]} \Sexpr{targetName} and \Sexpr{mainResults[params$primary,"comparatorSubjects"]} \Sexpr{comparatorName} patients for the primary analysis, totaling \Sexpr{round(mainResults[params$primary,"targetDays"]/365.24)} and \Sexpr{round(mainResults[params$primary,"comparatorDays"]/365.24)} patient-years of observation, and \Sexpr{mainResults[params$primary,"targetOutcomes"]} and \Sexpr{mainResults[params$primary,"comparatorOutcomes"]} events respectively.
We control for measured confounding using propensity score trimming and stratification based on an expansive propensity score model that includes all measured patient features before treatment initiation.
We account for unmeasured confounding using negative and positive controls to estimate and adjust for residual systematic bias in the study design and data source, providing calibrated confidence intervals and p-values.
In terms of \Sexpr{outcomeName}, \Sexpr{targetName} has a 
\Sexpr{judgeHazardRatio(mainResults[params$primary,"calibratedCi95Lb"], mainResults[params$primary,"calibratedCi95Ub"])}
risk as \Sexpr{comparatorName} [HR: \Sexpr{prettyHr(mainResults[params$primary,"calibratedRr"])},
95\% confidence interval (CI) \Sexpr{prettyHr(mainResults[params$primary, "calibratedCi95Lb"])} - \Sexpr{prettyHr(mainResults[params$primary, "calibratedCi95Ub"])}].
We demonstrate (TODO) \Sexpr{judgePropensityScore(1.1,1.1)}.
%In conclusion, we find that \Sexpr{targetName} is \Sexpr{judgeEffectiveness(mainResults[params$primary,"calibratedCi95Lb"], mainResults[params$primary,"calibratedCi95Ub"])} effective as \Sexpr{comparatorName} in preventing \Sexpr{outcomeName}.
\end{abstract}

\dates{This manuscript was compiled on \today}
% \doi{\url{www.pnas.org/cgi/doi/10.1073/pnas.XXXXXXXXXX}}

\begin{document}
\SweaveOpts{concordance=TRUE}

% Optional adjustment to line up main text (after abstract) of first page with line numbers, when using both lineno and twocolumn options.
% You should only change this length when you've finalised the article contents.
\verticaladjustment{-2pt}

\maketitle
\thispagestyle{firststyle}
\ifthenelse{\boolean{shortarticle}}{\ifthenelse{\boolean{singlecolumn}}{\abscontentformatted}{\abscontent}}{}

% If your first paragraph (i.e. with the \dropcap) contains a list environment (quote, quotation, theorem, definition, enumerate, itemize...), the line after the list may have some extra indentation. If this is the case, add \parshape=0 to the end of the list environment.

\acknow{We are grateful for \ldots.}

The Large-scale Evidence Generation and Evaluation in a Network of Databases (LEGEND) project aims to generate reliable evidence on the effects of medical interventions using observational healthcare data to support clinical decision making.
LEGEND follows ten guiding principles (see Supplementary Material); chief among these stand that we generate evidence at large-scale to achieve completeness and faciliate analysis of the overall distribution of effect size estimates across treatments and outcomes.  
We also generate evidence consistently by applying a systematic approach across all research questions and disseminate evidence regardless on the estimates effects to avoid publication bias. These aims help overcome the questionable reliable of observational research [schuemie2018].
This LEGEND document reports the risk of \Sexpr{outcomeName} between new users of \Sexpr{targetName} and \Sexpr{comparatorName} treated for \Sexpr{params$indication}.

\hypertarget{methods}{%
\section*{Methods}\label{methods}}
\addcontentsline{toc}{section}{Methods}

\subsection*{Data source}
We conduct a new-user cohort study comparing new users of \Sexpr{targetName} with new users of \Sexpr{comparatorName} in the \Sexpr{params$databaseName} (\Sexpr{params$databaseId}) database encoded in the Observational Medical Outcomes Partnership (OMOP) common data model (CDM) version 5 %\citep{hripcsak2015observational,overhage2012validation,ryan2013empirical}
.

\subsection*{Study design}
This study follows a retrospective, observational, comparative cohort design %\citep{ryan2013empirical}
.
We include patients 18 years old or older who are first time users of \Sexpr{targetName} or \Sexpr{comparatorName} from XXX to XXX, and who have a diagnosis of \Sexpr{params$indication} (when?) prior to treatment initation.
We require that patients have continuous observation in the database for at least (how long?) year prior to treatment initiation.
We exclude patients with prior \Sexpr{outcomeName} events and less than 1 day at risk.
Full cohort details, include concept codes, are provided in the Supplementary Inforamtion (add link).
The outcome of interest is \Sexpr{outcomeName}. 
We begin the outcome risk window 1 day after treatment initation.
As our primary analysis, we have pre-specified \ldots
We end the outcome time-at-risk window when the patient is no longer observable in the database, analogous to an intent-to-treat design.
We end the outcome time-at-risk window at first cessation of continuous drug exposure, analogous to an on-treatment design. 
Continuous drug exposures are constructed from the available longitudinal data by considering sequential prescriptions that have fewer than 30 days gap between prescriptions.

\subsection*{Statistical analysis}
We conduct our cohort study using the open-source OHDSI CohortMethod R package %\citep{schuemie2017cohort}
, with large-scale analytics achieved through the Cyclops R package %\citep{suchard2013high?}
.
We use propensity scores (PSs) -- estimates of treatment exposure probability conditional on pre-treatment baseline features in the one year prior to treatment initiation -- to control for potential measured confoudning and improve balance between the target (\Sexpr{targetName}) and comparator (\Sexpr{comparatorName}) cohorts %\citep{rosenbaum1983central}
.
We use an expansive PS model that includes all available patient demographics, drug, condition and procedure covariates generated through the FeatureExtraction R package %\citep{schuemie2018feature}
 instead of a prespecified set of investigator-selected confounders.
 We perform PS trimming and stratification and then estimate comparative \Sexpr{targetName}-vs-\Sexpr{comparatorName} hazard ratios (HRs) using a Cox proportional hazards model.
 Detailed covariate and methods informations are provided in the Supplementary Information (add link).
 We present PS and covariate balance metrics to assess successful confounding control, and provide HR estimates with and without prespecified subgroup intervation terms and Kaplan-Meier survival plots for the outcome of \Sexpr{outcomeName}.
 Subgroups include \ldots (and how to know when there are insufficient patients in a subgroup to report estimate?).
 
Residual study bias from unmeasured and systematic sources can exist in observational studies after controlling for measured confounding %\citep{schuemie2018reliable}
.
To estimate such residual bias, we conduct negative control outcome experiments with (XXX) negative control outcomes %\citep{negative-controls}
identified through a data-rich algorithm %\citep{voss2017accuracy}
.
We fit the negative control estimates to an empirical null distribution that characterizes the study residual bias and is an important artifact from which to assess the study design %\citep{schuemie2014interpreting,schuemie2018empirical}
.
Using the empirical null distribution and synthetic positive controls %\citep{positive-controls}
, we additionally calibrate all HR estimates, their 95\% confidence intervals (CIs) and the $p$-value to reject the null hypothesis of no differential effect (HR = 1).
 
\hypertarget{results}{%
\section*{Results}\label{results}}
\addcontentsline{toc}{section}{Results}

\subsection*{Population characteristics}

Figure \ref{fig:attrition} diagrams the inclusion of study subjects from the \Sexpr{params$databaseId} database.
For the intent-to-treatment analysis, we identify \Sexpr{mainResults[params$itt,"targetSubjects"]} \Sexpr{targetName} and \Sexpr{mainResults[params$itt,"comparatorSubjects"]} \Sexpr{comparatorName} patients, totaling \Sexpr{round(mainResults[params$itt,"targetDays"]/365.24)} and \Sexpr{round(mainResults[params$itt,"comparatorDays"]/365.24)} patient-years of observation, and \Sexpr{mainResults[params$itt,"targetOutcomes"]} and \Sexpr{mainResults[params$itt,"comparatorOutcomes"]} events respectively.
Similarly, for the on-treatment analylsis, we identify \Sexpr{mainResults[params$ot,"targetSubjects"]} \Sexpr{targetName} and \Sexpr{mainResults[params$ot,"comparatorSubjects"]} \Sexpr{comparatorName} patients, totaling \Sexpr{round(mainResults[params$ot,"targetDays"]/365.24)} and \Sexpr{round(mainResults[params$ot,"comparatorDays"]/365.24)} patient-years of observation, and \Sexpr{mainResults[params$ot,"targetOutcomes"]} and \Sexpr{mainResults[params$ot,"comparatorOutcomes"]} events respectively.
<<attrition_plot, echo=FALSE, cache=TRUE>>==
plot <- drawAttritionDiagram(attrition, targetName, comparatorName)
suppressMessages(ggsave("attrition.pdf", plot,
                        width = 6, height = 10, units = "in"))
@
%
\begin{figure}
  \vspace*{-1em}
  \centerline{\includegraphics[width=0.45\textwidth]{attrition}}
  \vspace*{-2em}
  \caption{\textbf{Attrition diagram for selecting new-users of \Sexpr{targetName} and \Sexpr{comparatorName} from the \Sexpr{params$databaseId} database.}}
  \label{fig:attrition}
\end{figure}
%
Table \ref{tab:demographics} compares base-line characteristics between patient cohorts.
%
\begin{table}
\caption{\textbf{Patient demographics.} Target (T) population is sertaline new-users.  Comparative (C) population is dulexotine new-users.  We report the standardized difference of population means (StdDiff) before and after stratification for selected base-line patient characteristics.}\label{tab:demographics}
\vspace*{-0.5em}
\centerline{
\resizebox{0.5\textwidth}{!}{
\begin{tabular}{lrrrrrr}
\hline
& \multicolumn{3}{c}{Before stratification}
& \multicolumn{3}{c}{After stratification} \\
\multicolumn{1}{c}{Characteristic}
  & \multicolumn{1}{c}{T (\%)}
  & \multicolumn{1}{c}{C (\%)}
  & \multicolumn{1}{c}{StdDiff}
  & \multicolumn{1}{c}{T (\%)}
  & \multicolumn{1}{c}{C (\%)}
  & \multicolumn{1}{c}{StdDiff} \\
  \hline
<<features, echo=FALSE, results=tex, cache=TRUE>>==
table <- prepareTable1(balance)
table <- table[3:nrow(table),]

print(xtable(table, format = "latex", align = c("l","l","r","r","r","r","r","r")),
      include.rownames = FALSE,
      include.colnames = FALSE,
      hline.after = NULL,
      only.contents = TRUE,
      sanitize.text.function = identity)
@
\hline
\end{tabular}
}
}
\end{table}

\subsection*{Patient characteristics balance}
Figure \ref{fig:ps} plots the preference score distributions, re-scalings of PS estimates to adjust for differential treatment prevalences, for patients treated with \Sexpr{targetName} and \Sexpr{comparatorName}.
We assess characteristics balance achieved through PS adjustment by comparing all characteristics' standardized difference (StdDiff) between treatment group means before and after PS trimming and stratification (Table \ref{tab:demographics}).
Figure \ref{fig:balance} plots StdDiff for all \Sexpr{nrow(balance)} base-line patient features that serve as input for the PS model.
Before stratification, \Sexpr{sum(na.omit(balance$beforeMatchingStdDiff) > 0.1)} features have a StdDiff $> 0.1$.  After stratification, the count is \Sexpr{sum(na.omit(balance$afterMatchingStdDiff) > 0.1)}.
%
<<make_ps, echo=FALSE, cache=TRUE>>==
plot <- plotPs(ps, targetName, comparatorName)
suppressMessages(ggsave("ps.pdf", plot,
                        width = 5, height = 5, units = "in"))
@
%
\begin{figure}
  \centerline{
    \includegraphics[width=0.35\textwidth]{ps}
  }
  \caption{\textbf{Preference score distribution for sertaline and dulexotine new-users.}
  The preference score is a transformation of the propensity score that adjusts for prevalence differences between populations.  A higher overlap indicates that subjects in the two populations are more similar in terms of their predicted probability of receiving one treatment over the other.
  }
  \label{fig:ps}
\end{figure}
%
<<make_balance, echo=FALSE, cache=TRUE>>==
plot <- CohortMethod::plotCovariateBalanceScatterPlot(balance)
suppressMessages(ggsave("balance.pdf", plot,
                        width = 5, height = 5, units = "in"))
@
%
\begin{figure}
  \centerline{
    \includegraphics[width=0.35\textwidth]{balance}
  }
  \caption{\textbf{Patient characteristics balance before and after stratification.} As a rule-of-thumb, all values $< 0.1$ is generally considered well-balanced (add citation).}
  \label{fig:balance}
\end{figure}
%
(TODO) Add judgement statement about measured confounding control using something like: \Sexpr{judgePropensityScore(1.1,1.1)}
%
Finally, Figure \ref{fig:topTen} presents the top ten most imbalanced characteristics before and after stratification.
%
<<make_features, echo=FALSE, cache=TRUE>>==
plot <- CohortMethod::plotCovariateBalanceOfTopVariables(balance, n = 10,
                                                         beforeLabel = "before",
                                                         afterLabel = "after",
                                                         maxNameWidth = 50)
plot$theme$legend.direction <- "horizontal"
suppressMessages(ggsave("top_10.pdf", plot,
                        width = 5, height = 3.5, units = "in"))
@
%
\begin{figure}
  \centerline{
    \includegraphics[width=0.5\textwidth]{top_10}
  }
  \caption{\textbf{Top ten most imbalanced patient characteristics before and after stratification.}}
  \label{fig:topTen}
\end{figure}
%


\subsection*{Outcome assessment}

Table \ref{tab:hr} reports estimated HRs comparing \Sexpr{targetName} to \Sexpr{comparatorName} for both the intent-to-treat and on-treatment designs.
The table also presents HRs after adjusting for possible subgroup differences (how we know which subgroups?).
%
\begin{table*}
\caption{Hazard ratio (HR) estimates and their confidence intervals (CIs) and $p$-value to reject the null hypothesis of no difference (HR = 1) under various designs.}
\label{tab:hr}
\vspace*{-0.5em}
\centerline{
\begin{tabular}{lrrrr}
\hline
& \multicolumn{2}{c}{Uncalibrated} & \multicolumn{2}{c}{Calibrated} \\
\multicolumn{1}{c}{Design} 
& \multicolumn{1}{c}{HR (95\% CI)} & \multicolumn{1}{c}{$p$-value}
& \multicolumn{1}{c}{HR (95\% CI)} & \multicolumn{1}{c}{$p$-value} \\
\hline
<<result_table, echo=FALSE, results=tex>>==
table <- mainResults
table$hr <- sprintf("%.2f (%.2f - %.2f)", mainResults$rr, mainResults$ci95lb, mainResults$ci95ub)
table$p <- sprintf("%.2f", table$p)
table$calHr <- sprintf("%.2f (%.2f - %.2f)", mainResults$calibratedRr, mainResults$calibratedCi95Lb, mainResults$calibratedCi95Ub)
table$calibratedP <- sprintf("%.2f", table$calibratedP)
table <- merge(table, analyses)
table <- table[, c("description", "hr", "p", "calHr", "calibratedP")]

print(xtable(table),
      include.rownames = FALSE,
      include.colnames = FALSE,
      hline.after = NULL,
      only.contents = TRUE,
      sanitize.text.function = identity)
@
\hline
\end{tabular}
}
\end{table*}
%
Figure \ref{fig:km} plots Kaplan-Meier survival curves for patients under the intent-to-treat design.
\begin{itemize}
  \item Insert KM plot
\end{itemize}

\subsection*{Residual bias}
In the absense of bias, we expect 95\% of negative control estimate 95\% confidence intervals to include the presumed null hypothesis HR = 1.  Figure \ref{fig:negatives} describes the negative control estimates under both the intent-to-treat and on-treatment designs.
%
(TODO) Add judgement statement about residual bias control, using something like: \Sexpr{judgePropensityScore(1.1,1.1)}.
\begin{itemize}
  \item Insert negative control plots
\end{itemize}

\hypertarget{conclusions}{%
\section*{Conclusions}\label{conclusions}}
\addcontentsline{toc}{section}{Conclusions}

We find that \Sexpr{targetName} has a 
\Sexpr{judgeHazardRatio(mainResults[params$primary,"calibratedCi95Lb"], mainResults[params$primary,"calibratedCi95Ub"])}
risk of \Sexpr{outcomeName} as \Sexpr{comparatorName} within the population that the \Sexpr{params$databaseId} represents.
(What else?)

\hypertarget{supporting-information-si}{%
\subsection*{Supporting Information
(SI)}\label{supporting-information-si}}
\addcontentsline{toc}{subsection}{Supporting Information (SI)}

Here we provide extended details on study cohorts and design and the guiding principles of LEGEND.

\hypertarget{si-principles}{%
\subsubsection*{SI LEGEND Principles}\label{si-text}}
\addcontentsline{toc}{subsubsection}{SI Principles} (Need to re-order these)

\begin{enumerate}[noitemsep]
  \item Evidence will be generated at large-scale.
  \item Dissemination of the evidence will not depend on the estimated effects.
  \item Evidence will be generated by consistently applying a systematic approach across all research questions.
  \item Evidence will be generated using a pre-specified analysis design.
  \item Evidence will be generated using open source software that is freely available to all.
  \item Evidence generation process will be empirically evaluated by including control research questions where the true effect size is known.
  \item Evidence will be generated using best-practices.
  \item LEGEND will not be used to evaluate methods.
  \item Evidence will be updated on a regular basis.
  \item No patient-level data will be shared between sites in the network, only aggregated data.
\end{enumerate}

\subsubsection*{SI \Sexpr{capitalize(targetName)} cohort definition}
(TODO)

\subsubsection*{SI \Sexpr{capitalize(comparatorName)} cohort definition}
(TODO)

\subsubsection*{SI \Sexpr{capitalize(outcomeName)} cohort definition}
(TODO)

\subsubsection*{SI Covariate sets}
\begin{itemize}[noitemsep]
\item Demographics (age in 5-year increments, gender, year of index date)
\item Condition Occurrence (condition occurrence in lookback window)
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 180 days prior to index date
  \item in 30 days prior to index date
  \end{itemize}
\item Condition Era (span of time when person assumed to have condition)
  \begin{itemize}[noitemsep]
  \item ever
  \item overlapping with index date
  \end{itemize}
\item Drug Exposure (drug occurrence in lookback window)
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 30 days prior to index date
  \end{itemize}
\item Drug Era (span of time when person assumed to have drug)
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 30 days prior to index date
  \item ever
  \item overlapping with index date
  \end{itemize}
\item Procedure Occurrence
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 30 days prior to index date
  \end{itemize}
\item Observation
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 30 days prior to index date
  \item observations count in 365 days prior to index date
  \end{itemize}
\item Measurement
  \begin{itemize}[noitemsep]
  \item in 365 days prior to index date
  \item in 30 days prior to index date
  \item high measurement in 180 days prior to index date
  \item low measurement in 180 days prior to index date
  \item measurements count in 365 days prior to index date
  \end{itemize}
\item Concepts Count in 365 days prior to index date
\item Risk Scores (Charlson, DCSI, CHADS2)
\end{itemize}

\subsubsection*{SI Anticoagulants Study Negative Controls}
Negative controls were selected using the following criteria:
\begin{itemize}[noitemsep]
  \item No evidence found in literature on clinical trials using the method proposed by Avillach %\citep{avillach2012design}
  \item No evidence found in literature using the method used in SemMedDB %\citep{kilicoglu2011constructing}
  \item No evidence found in the structured product label (US and EU).
  \item FAERS Proportional Reporting Ratio (PRR) needed to be less than 2.
\end{itemize}

Negative controls were rank-ordered by prevalence in study cohort, and manually reviewed until 50 controls were selected. Negative controls with fewer than $0.02\%$ prevalence were discarded. See Table \ref{tab:negatives}
%
%\vspace*{-2em}
\begin{table}
\caption{Negative controls employed with \Sexpr{params$indication} patients.}
\label{tab:negatives}
\vspace*{-1em}
\begin{tabular}{ll}
\hline
% \begin{table}[t]{  |p{8.1cm} | p{8.1cm} |} \hline
Acute bronchitis & Allergic rhinitis \\
Anxiety disorder & Arthritis of spine \\
Arthropathy of knee joint & Atelectasis \\
Barrett's esophagus & Blepharitis \\
Bronchiectasis & Bundle branch block \\
Cellulitis & Chronic sinusitis \\
Chronic ulcer of skin & Communication disorder \\
Crohn's disease & Curvature of spine \\
Cutis laxa & Diabetic renal disease \\
Diabetic retinopathy & Dislocation of joint \\
Dyssomnia & Dysuria \\
Effusion of joint & Fracture of upper limb \\
Gallstone & Gammopathy \\
Human papilloma virus infection & Hyperplasia of prostate \\
Inflammation of sacroiliac joint & Ingrowing nail \\
Malignant tumor of breast & Multiple sclerosis \\
Neck pain & Neurologic disorder associated \\
& $\quad$ with diabetes mellitus \\
Obesity & Osteomyelitis \\
Otitis media & Peripheral vertigo \\
Plantar fasciitis & Presbyopia \\
Prolapse of female genital organs & Psychotic disorder \\
Seborrheic keratosis & Simple goiter \\
Sleep apnea & Superficial mycosis \\
Urge incontinence of urine & Urinary tract infectious disease \\
Verruca vulgaris & \\
\hline
% \end{table}
\end{tabular}
\end{table}

% \hypertarget{appendices}{%
% \subsubsection*{Appendices}\label{appendices}}
% \addcontentsline{toc}{subsubsection}{Appendices}
% 
% PNAS prefers that authors submit individual source files to ensure
% readability. If this is not possible, supply a single PDF file that
% contains all of the SI associated with the paper. This file type will be
% published in raw format and will not be edited or composed.

\showmatmethods
\showacknow
\pnasbreak

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-belkin2002using}{}%
1. Belkin M, Niyogi P (2002) Using manifold stucture for partially
labeled classification. \emph{Advances in Neural Information Processing
Systems}, pp 929--936.

\leavevmode\hypertarget{ref-berard1994embedding}{}%
2. Bérard P, Besson G, Gallot S (1994) Embedding riemannian manifolds by
their heat kernel. \emph{Geometric \& Functional Analysis GAFA}
4(4):373--398.

\leavevmode\hypertarget{ref-coifman2005geometric}{}%
3. Coifman RR, et al. (2005) Geometric diffusions as a tool for harmonic
analysis and structure definition of data: Diffusion maps.
\emph{Proceedings of the National Academy of Sciences of the United
States of America} 102(21):7426--7431.



% Bibliography
% \bibliography{pnas-sample}

\end{document}

