\documentclass[9pt,twocolumn,twoside,]{pnas-new}

%% Some pieces required from the pandoc template
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Use the lineno option to display guide line numbers if required.
% Note that the use of elements such as single-column equations
% may affect the guide line number alignment.


\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

<<params, echo=FALSE, message=FALSE, comment=FALSE, results=hide>>=
params <- list(databaseId = "MDCR",
               targetId = 739138,
               comparatorId =  715259,
               outcomeId = 18,
               indication = tolower("major depressive disorder"))
@

<<setup, echo=FALSE, message=FALSE, comment=FALSE, results=hide>>=
library(DatabaseConnector)
library(CohortMethod)
library(Legend)
library(knitr)
library(xtable)
library(ggplot2)
source("DataPulls.R")
source("PlotsAndTables.R")
options(knitr.kable.NA = '')

useStoredObject <- TRUE

if (!useStoredObject) {
    connectionDetails <- createConnectionDetails(dbms = "postgresql",
                                                 server = "localhost/ohdsi",
                                                 user = "postgres",
                                                 password = Sys.getenv("pwPostgres"),
                                                 schema = "legend")
    connection <- connect(connectionDetails)
    targetName <- tolower(getExposureName(connection, params$targetId))
    comparatorName <- tolower(getExposureName(connection, params$comparatorId))
    outcomeName <- tolower(getOutcomeName(connection, params$outcomeId))
    analyses <- getAnalyses(connection)
    mainResults <- getMainResults(connection,
                                  targetIds = params$targetId,
                                  comparatorIds = params$comparatorId,
                                  outcomeIds = params$outcomeId,
                                  databaseIds = params$databaseId)

    attrition <- getAttrition(connection,
                              targetId = params$targetId,
                              comparatorId = params$comparatorId,
                              outcomeId = params$outcomeId,
                              analysisId = 1,
                              databaseId = params$databaseId)

    balance <- getCovariateBalance(connection,
                                   targetId = params$targetId,
                                   comparatorId = params$comparatorId,
                                   databaseId = params$databaseId)

    ps <- getPs(connection,
                targetId = params$targetId,
                comparatorId = params$comparatorId,
                databaseId = params$databaseId)

    kaplanMeier <- getKaplanMeier(connection,
                                  targetId = params$targetId,
                                  comparatorId = params$comparatorId,
                                  outcomeId = params$outcomeId,
                                  databaseId = params$databaseId,
                                  analysisId = 2)
} else {
    load("paperData.rda")
}
@

\templatetype{pnasresearcharticle}  % Choose template

\title{ \Sexpr{outcomeName} risk in new-users of \Sexpr{targetName} versus \Sexpr{comparatorName}
for \Sexpr{params$indication} in the \Sexpr{params$databaseId} database}

\author[a,b,c,1]{Martijn J. Schuemie}
\author[a,b,d]{Patrick B. Ryan}
\author[a,e]{Seng Chan You}
\author[a,f]{Nicole Pratt}
\author[a,g]{David Madigan}
\author[a,d]{George Hripcsak}
\author[a,c,h,i]{Marc A. Suchard}

  \affil[a]{Observational Health Data Sciences and Informatics, New York, NY, USA}
  \affil[b]{Janssen Research \& Development, Titusville, NJ, USA}
  \affil[c]{Department of Biostatistics, University of Califoria, Los Angeles, CA}
  \affil[d]{Department of Biomedical Informatics, Columbia University, New York, NY}
  \affil[e]{Department of Biomedical Informatics, Ajou University, Suwon, South
Korea}
  \affil[f]{Sansom Institute, University of South Australia, Adelaide SA, Australia}
  \affil[g]{Department of Statistics, Columbia University, New York, NY}
  \affil[h]{Department of Biomathematics, University of Califoria, Los Angeles, CA}
  \affil[i]{Department of Human Genetics, University of Califoria, Los Angeles, CA}


% Please give the surname of the lead author for the running footer
\leadauthor{Schuemie}

% Please add here a significance statement to explain the relevance of your work
\significancestatement{Authors must submit a 120-word maximum statement about the significance
of their research paper written at a level understandable to an
undergraduate educated scientist outside their field of speciality. The
primary goal of the Significance Statement is to explain the relevance
of the work in broad context to a broad readership. The Significance
Statement appears in the paper itself and is required for all research
papers.}


\authorcontributions{Please provide details of author contributions here.}

\authordeclaration{Please declare any conflict of interest here.}

\equalauthors{\textsuperscript{} }

\correspondingauthor{\textsuperscript{} }

% Keywords are not mandatory, but authors are strongly encouraged to provide them. If provided, please include two to five keywords, separated by the pipe symbol, e.g:
 \keywords{  one |  two |  optional |  optional |  optional   }

\begin{abstract}
We conduct a large-scale study on the incidence of \Sexpr{outcomeName} among new users of \Sexpr{targetName} and \Sexpr{comparatorName} from XXXX to XXXX in the \Sexpr{params$databaseId} database.
The primary outcome of interest is an estimate of the hazard ratio (HR) for incident events between comparable new users under an intent-to-treat risk window assumption.
We control for measured confounding using propensity score trimming and stratification based on an expansive propensity score model that includes all measured patient features before treatment initiation.
We account for unmeasured confounding using negative and positive controls to estimate and adjust for residual systematic bias in the study design and data source.
We identify \Sexpr{mainResults[1,"targetSubjects"]} \Sexpr{targetName} and \Sexpr{mainResults[1,"comparatorSubjects"]} \Sexpr{comparatorName} patients for the primary analysis, totaling \Sexpr{mainResults[1,"targetDays"]/365.24} and \Sexpr{mainResults[1,"comparatorDays"]/365.24} patient-years of observation, and \Sexpr{mainResults[1,"targetOutcomes"]} and \Sexpr{mainResults[1,"comparatorOutcomes"]} events respectively.
\end{abstract}

\dates{This manuscript was compiled on \today}
\doi{\url{www.pnas.org/cgi/doi/10.1073/pnas.XXXXXXXXXX}}

\begin{document}
\SweaveOpts{concordance=TRUE}

% Optional adjustment to line up main text (after abstract) of first page with line numbers, when using both lineno and twocolumn options.
% You should only change this length when you've finalised the article contents.
\verticaladjustment{-2pt}

\maketitle
\thispagestyle{firststyle}
\ifthenelse{\boolean{shortarticle}}{\ifthenelse{\boolean{singlecolumn}}{\abscontentformatted}{\abscontent}}{}

% If your first paragraph (i.e. with the \dropcap) contains a list environment (quote, quotation, theorem, definition, enumerate, itemize...), the line after the list may have some extra indentation. If this is the case, add \parshape=0 to the end of the list environment.

\acknow{Please include your acknowledgments here, set in a single paragraph.
Please do not include any acknowledgments in the Supporting Information,
or anywhere else in the manuscript.}

This document reports the risk of Stroke in new-users of Sertraline
vs.~duloxetine.

\hypertarget{methods}{%
\section*{Methods}\label{methods}}
\addcontentsline{toc}{section}{Methods}

\hypertarget{results}{%
\section*{Results}\label{results}}
\addcontentsline{toc}{section}{Results}

\begin{table*}
\caption{\textbf{Patient demographics.} Target (T) population is sertaline new-users.  Comparative (C) population is dulexotine new-users.  We report the standardized difference of population means (StdDiff) before and after stratification for selected base-line patient characteristics.}\label{tab:demographics}
\begin{center}
\resizebox{0.5\textwidth}{!}{
\begin{tabular}{lrrrrrr}
\hline
& \multicolumn{3}{c}{Before stratification}
& \multicolumn{3}{c}{After stratification} \\
\multicolumn{1}{c}{Characteristic}
  & \multicolumn{1}{c}{T (\%)}
  & \multicolumn{1}{c}{C (\%)}
  & \multicolumn{1}{c}{StdDiff}
  & \multicolumn{1}{c}{T (\%)}
  & \multicolumn{1}{c}{C (\%)}
  & \multicolumn{1}{c}{StdDiff} \\
  \hline
% latex table generated in R 3.4.3 by xtable 1.8-2 package
% Tue Aug 14 12:24:34 2018
 Age group &    &    &     &    &    &     \\ 
  $\quad$30-34 &  0.0 &  0.0 &     &  0.0 &  0.0 &     \\ 
  $\quad$35-39 &  0.0 &  0.0 &     &  0.0 &  0.0 &     \\ 
  $\quad$40-44 &  0.0 &  0.1 & -0.02 &  0.1 &  0.1 & -0.01 \\ 
  $\quad$45-49 &  0.2 &  0.5 & -0.05 &  0.3 &  0.3 &  0.00 \\ 
  $\quad$50-54 &  0.6 &  1.4 & -0.08 &  0.9 &  1.1 & -0.03 \\ 
  $\quad$55-59 &  1.4 &  2.7 & -0.09 &  1.9 &  2.2 & -0.02 \\ 
  $\quad$60-64 &  2.2 &  3.5 & -0.08 &  2.7 &  2.9 & -0.01 \\ 
  $\quad$65-69 & 18.2 & 22.0 & -0.10 & 20.7 & 20.3 &  0.01 \\ 
  $\quad$70-74 & 21.4 & 23.9 & -0.06 & 22.4 & 22.4 &  0.00 \\ 
  $\quad$75-79 & 19.9 & 19.5 &  0.01 & 19.7 & 19.4 &  0.01 \\ 
  $\quad$80-84 & 17.1 & 14.2 &  0.08 & 15.5 & 15.4 &  0.00 \\ 
  $\quad$85-89 & 12.3 &  8.9 &  0.11 & 10.8 & 11.1 & -0.01 \\ 
  $\quad$90-94 &  5.3 &  2.8 &  0.12 &  4.1 &  4.1 &  0.00 \\ 
  $\quad$95-99 &  1.2 &  0.5 &  0.08 &  1.0 &  0.7 &  0.03 \\ 
  $\quad$00-04 &  0.1 &  0.0 &  0.03 &  0.1 &  0.0 &  0.02 \\ 
  $\quad$05-09 &  0.0 &  0.0 &     &  0.0 &  0.0 &     \\ 
  Gender: female & 64.4 & 69.2 & -0.10 & 66.7 & 66.5 &  0.00 \\ 
  Medical history: General &    &    &     &    &    &     \\ 
  $\quad$Acute respiratory disease & 29.9 & 30.2 & -0.01 & 30.4 & 30.3 &  0.00 \\ 
  $\quad$Attention deficit hyperactivity disorder &  0.7 &  0.8 & -0.01 &  0.8 &  0.8 &  0.01 \\ 
  $\quad$Chronic liver disease &  1.5 &  1.5 &  0.00 &  1.6 &  1.5 &  0.01 \\ 
  $\quad$Chronic obstructive lung disease & 21.3 & 20.3 &  0.03 & 21.0 & 21.3 & -0.01 \\ 
  $\quad$Crohn's disease &  0.6 &  0.7 & -0.01 &  0.7 &  0.6 &  0.01 \\ 
  $\quad$Dementia & 19.0 & 12.1 &  0.19 & 15.6 & 16.1 & -0.01 \\ 
  $\quad$Depressive disorder & 86.8 & 84.6 &  0.06 & 86.7 & 86.5 &  0.01 \\ 
  $\quad$Diabetes mellitus & 28.5 & 28.7 &  0.00 & 28.3 & 28.9 & -0.02 \\ 
  $\quad$Gastroesophageal reflux disease & 22.5 & 22.5 &  0.00 & 22.6 & 22.4 &  0.00 \\ 
  $\quad$Gastrointestinal hemorrhage &  6.8 &  6.3 &  0.02 &  6.5 &  6.7 & -0.01 \\ 
  $\quad$Human immunodeficiency virus infection &  0.2 &  0.2 &  0.00 &  0.2 &  0.1 &  0.01 \\ 
  $\quad$Hyperlipidemia & 49.2 & 44.5 &  0.09 & 47.1 & 47.5 & -0.01 \\ 
  $\quad$Hypertensive disorder & 71.0 & 66.5 &  0.10 & 69.0 & 69.3 &  0.00 \\ 
  $\quad$Lesion of liver &  1.7 &  1.0 &  0.06 &  1.4 &  1.1 &  0.03 \\ 
  $\quad$Obesity &  8.1 &  8.2 &  0.00 &  8.3 &  8.5 & -0.01 \\ 
  $\quad$Osteoarthritis & 42.6 & 53.0 & -0.21 & 48.3 & 47.6 &  0.01 \\ 
  $\quad$Pneumonia & 13.1 & 11.6 &  0.05 & 12.4 & 12.9 & -0.02 \\ 
  $\quad$Psoriasis &  1.4 &  1.5 &  0.00 &  1.4 &  1.3 &  0.01 \\ 
  $\quad$Renal impairment & 19.8 & 14.6 &  0.14 & 17.3 & 17.5 &  0.00 \\ 
  $\quad$Rheumatoid arthritis &  3.0 &  4.3 & -0.07 &  3.8 &  3.8 &  0.00 \\ 
  $\quad$Schizophrenia &  0.0 &  0.0 &  0.01 &  0.0 &  0.0 &  0.00 \\ 
  $\quad$Ulcerative colitis &  0.7 &  0.8 & -0.01 &  0.7 &  0.8 & -0.02 \\ 
  $\quad$Urinary tract infectious disease & 24.3 & 22.7 &  0.04 & 23.9 & 24.3 & -0.01 \\ 
  $\quad$Viral hepatitis C &  0.5 &  0.4 &  0.01 &  0.5 &  0.4 &  0.02 \\ 
  $\quad$Visual system disorder & 52.7 & 51.4 &  0.02 & 52.0 & 51.8 &  0.00 \\ 
  Medical history: Cardiovascular disease &    &    &     &    &    &     \\ 
  $\quad$Atrial fibrillation & 17.9 & 13.7 &  0.12 & 15.8 & 16.6 & -0.02 \\ 
  $\quad$Cerebrovascular disease & 17.5 & 15.1 &  0.06 & 16.4 & 16.6 &  0.00 \\ 
  $\quad$Coronary arteriosclerosis & 27.9 & 25.6 &  0.05 & 26.9 & 27.1 & -0.01 \\ 
  $\quad$Heart disease & 57.3 & 52.4 &  0.10 & 55.2 & 55.2 &  0.00 \\ 
  $\quad$Heart failure & 19.3 & 15.7 &  0.09 & 17.4 & 18.2 & -0.02 \\ 
  $\quad$Ischemic heart disease & 16.2 & 14.5 &  0.05 & 15.2 & 15.3 &  0.00 \\ 
  $\quad$Peripheral vascular disease & 35.7 & 32.5 &  0.07 & 34.2 & 34.4 &  0.00 \\ 
  $\quad$Pulmonary embolism &  2.0 &  2.2 & -0.01 &  2.0 &  2.2 & -0.02 \\ 
  $\quad$Venous thrombosis &  6.6 &  6.2 &  0.02 &  6.3 &  6.8 & -0.02 \\ 
  Medical history: Neoplasms &    &    &     &    &    &     \\ 
  $\quad$Hematologic neoplasm &  2.5 &  2.2 &  0.02 &  2.4 &  2.3 &  0.00 \\ 
  $\quad$Malignant lymphoma &  1.2 &  1.1 &  0.01 &  1.3 &  1.1 &  0.02 \\ 
  $\quad$Malignant neoplasm of anorectum &  0.6 &  0.4 &  0.02 &  0.5 &  0.4 &  0.01 \\ 
  $\quad$Malignant neoplastic disease & 20.5 & 18.7 &  0.04 & 19.9 & 19.8 &  0.00 \\ 
  $\quad$Malignant tumor of breast &  3.8 &  3.8 &  0.00 &  4.1 &  3.7 &  0.02 \\ 
  $\quad$Malignant tumor of colon &  1.1 &  0.9 &  0.02 &  1.0 &  1.0 & -0.01 \\ 
  $\quad$Malignant tumor of lung &  1.1 &  1.1 &  0.00 &  1.0 &  1.2 & -0.02 \\ 
  $\quad$Malignant tumor of urinary bladder &  1.1 &  1.0 &  0.02 &  1.1 &  1.1 &  0.00 \\ 
  $\quad$Primary malignant neoplasm of prostate &  2.5 &  2.4 &  0.01 &  2.4 &  2.6 & -0.01 \\ 
  Medication use &    &    &     &    &    &     \\ 
  $\quad$Agents acting on the renin-angiotensin system & 51.3 & 50.3 &  0.02 & 51.1 & 50.6 &  0.01 \\ 
  $\quad$Antibacterials for systemic use & 68.6 & 73.0 & -0.10 & 70.8 & 70.8 &  0.00 \\ 
  $\quad$Antiepileptics & 33.7 & 48.6 & -0.31 & 41.0 & 40.2 &  0.02 \\ 
  $\quad$Antiinflammatory and antirheumatic products & 29.4 & 39.3 & -0.21 & 34.4 & 34.2 &  0.00 \\ 
  $\quad$Antineoplastic agents &  4.7 &  5.5 & -0.04 &  5.0 &  5.2 & -0.01 \\ 
  $\quad$Antipsoriatics &  1.1 &  1.2 & -0.01 &  1.1 &  1.3 & -0.01 \\ 
  $\quad$Antithrombotic agents & 30.6 & 28.9 &  0.04 & 29.9 & 29.9 &  0.00 \\ 
  $\quad$Beta blocking agents & 47.6 & 44.0 &  0.07 & 46.1 & 46.4 &  0.00 \\ 
  $\quad$Calcium channel blockers & 32.8 & 31.5 &  0.03 & 32.3 & 32.0 &  0.00 \\ 
  $\quad$Diuretics & 45.1 & 46.1 & -0.02 & 45.4 & 45.7 &  0.00 \\ 
  $\quad$Drugs for acid related disorders & 45.6 & 51.9 & -0.13 & 48.6 & 48.6 &  0.00 \\ 
  $\quad$Drugs for obstructive airway diseases & 35.1 & 38.2 & -0.06 & 36.5 & 36.0 &  0.01 \\ 
  $\quad$Drugs used in diabetes & 22.6 & 23.5 & -0.02 & 23.0 & 23.2 &  0.00 \\ 
  $\quad$Immunosuppressants &  4.8 &  6.5 & -0.07 &  5.5 &  5.7 & -0.01 \\ 
  $\quad$Lipid modifying agents & 57.1 & 57.5 & -0.01 & 57.1 & 57.5 & -0.01 \\ 
  $\quad$Opioids & 36.7 & 51.0 & -0.29 & 44.3 & 43.3 &  0.02 \\ 
  $\quad$Psycholeptics & 64.0 & 71.2 & -0.16 & 67.5 & 67.4 &  0.00 \\ 
  $\quad$Psychostimulants, agents used for adhd and nootropics &  4.8 &  8.6 & -0.15 &  6.5 &  6.6 &  0.00 \\ 
  
\end{tabular}
}
\end{center}
\end{table*}

\begin{figure}
  \centerline{
    \includegraphics[width=0.4\textwidth]{ps}
  }
  \caption{\textbf{Preference score distribution for sertaline and dulexotine new-users.}
  The preference score is a transformation of the propensity score that adjusts for size differences between populations.  A higher overlap indicates that subjects in the two populations are more similar in terms of their predicted probability of receiving one treatment over the other.
  }
\end{figure}

More text here.

\begin{table*}
\begin{tabular}{lrrrr}
% latex table generated in R 3.4.3 by xtable 1.8-2 package
% Tue Aug 14 14:06:11 2018
 PS stratification, on-treatment & 0.93 (0.68 - 1.26) & 0.64 & 0.91 (0.65 - 1.31) & 0.62 \\ 
  PS stratification, intent-to-treat & 1.01 (0.87 - 1.16) & 0.93 & 0.97 (0.81 - 1.18) & 0.86 \\ 
  PS stratification, on-treatment, subgroup interactions & 1.24 (0.16 - 7.81) & 0.83 & NA (NA - NA) & 0.87 \\ 
  PS stratification, intent-to-treat, subgroup interactions & 0.58 (0.28 - 1.12) & 0.12 & NA (NA - NA) & 0.12 \\ 
  
\end{tabular}
\end{table*}

\hypertarget{guide-to-using-this-template}{%
\section*{Guide to using this
template}\label{guide-to-using-this-template}}
\addcontentsline{toc}{section}{Guide to using this template}

Please note that whilst this template provides a preview of the typeset
manuscript for submission, to help in this preparation, it will not
necessarily be the final publication layout. For more detailed
information please see the
\href{http://www.pnas.org/site/authors/format.xhtml}{PNAS Information
for Authors}.

\hypertarget{author-affiliations}{%
\subsection*{Author Affiliations}\label{author-affiliations}}
\addcontentsline{toc}{subsection}{Author Affiliations}

Include department, institution, and complete address, with the
ZIP/postal code, for each author. Use lower case letters to match
authors with institutions, as shown in the example. Authors with an
ORCID ID may supply this information at submission.

\hypertarget{submitting-manuscripts}{%
\subsection*{Submitting Manuscripts}\label{submitting-manuscripts}}
\addcontentsline{toc}{subsection}{Submitting Manuscripts}

All authors must submit their articles at
\href{http://www.pnascentral.org/cgi-bin/main.plex}{PNAScentral}. If you
are using Overleaf to write your article, you can use the ``Submit to
PNAS'' option in the top bar of the editor window.

\hypertarget{format}{%
\subsection*{Format}\label{format}}
\addcontentsline{toc}{subsection}{Format}

Many authors find it useful to organize their manuscripts with the
following order of sections; Title, Author Affiliation, Keywords,
Abstract, Significance Statement, Results, Discussion, Materials and
methods, Acknowledgments, and References. Other orders and headings are
permitted.

\hypertarget{manuscript-length}{%
\subsection*{Manuscript Length}\label{manuscript-length}}
\addcontentsline{toc}{subsection}{Manuscript Length}

PNAS generally uses a two-column format averaging 67 characters,
including spaces, per line. The maximum length of a Direct Submission
research article is six pages and a PNAS PLUS research article is ten
pages including all text, spaces, and the number of characters displaced
by figures, tables, and equations. When submitting tables, figures,
and/or equations in addition to text, keep the text for your manuscript
under 39,000 characters (including spaces) for Direct Submissions and
72,000 characters (including spaces) for PNAS PLUS.

\hypertarget{references}{%
\subsection*{References}\label{references}}
\addcontentsline{toc}{subsection}{References}

References should be cited in numerical order as they appear in text;
this will be done automatically via bibtex, e.g. (1) and (2, 3). All
references, including for the SI, should be included in the main
manuscript file. References appearing in both sections should not be
duplicated. SI references included in tables should be included with the
main reference section.

\hypertarget{data-archival}{%
\subsection*{Data Archival}\label{data-archival}}
\addcontentsline{toc}{subsection}{Data Archival}

PNAS must be able to archive the data essential to a published article.
Where such archiving is not possible, deposition of data in public
databases, such as GenBank, ArrayExpress, Protein Data Bank, Unidata,
and others outlined in the Information for Authors, is acceptable.

\hypertarget{language-editing-services}{%
\subsection*{Language-Editing
Services}\label{language-editing-services}}
\addcontentsline{toc}{subsection}{Language-Editing Services}

Prior to submission, authors who believe their manuscripts would benefit
from professional editing are encouraged to use a language-editing
service (see list at www.pnas.org/site/authors/language-editing.xhtml).
PNAS does not take responsibility for or endorse these services, and
their use has no bearing on acceptance of a manuscript for publication.

\begin{figure}
\centering
\includegraphics{frog.png}
\caption{Placeholder image of a frog with a long example caption to show
justification setting.{}}
\end{figure}

\hypertarget{sec:figures}{%
\subsection*{Digital Figures}\label{sec:figures}}
\addcontentsline{toc}{subsection}{Digital Figures}

Only TIFF, EPS, and high-resolution PDF for Mac or PC are allowed for
figures that will appear in the main text, and images must be final
size. Authors may submit U3D or PRC files for 3D images; these must be
accompanied by 2D representations in TIFF, EPS, or high-resolution PDF
format. Color images must be in RGB (red, green, blue) mode. Include the
font files for any text.

Figures and Tables should be labelled and referenced in the standard way
using the \texttt{\textbackslash{}label\{\}} and
\texttt{\textbackslash{}ref\{\}} commands.

Figure \[fig:frog\] shows an example of how to insert a column-wide
figure. To insert a figure wider than one column, please use the
\texttt{\textbackslash{}begin\{figure*\}...\textbackslash{}end\{figure*\}}
environment. Figures wider than one column should be sized to 11.4 cm or
17.8 cm wide.

\hypertarget{single-column-equations}{%
\subsection*{Single column equations}\label{single-column-equations}}
\addcontentsline{toc}{subsection}{Single column equations}

Authors may use 1- or 2-column equations in their article, according to
their preference.

To allow an equation to span both columns, options are to use the
\texttt{\textbackslash{}begin\{figure*\}...\textbackslash{}end\{figure*\}}
environment mentioned above for figures, or to use the
\texttt{\textbackslash{}begin\{widetext\}...\textbackslash{}end\{widetext\}}
environment as shown in equation \[eqn:example\] below.

Please note that this option may run into problems with floats and
footnotes, as mentioned in the \href{http://texdoc.net/pkg/cuted}{cuted
package documentation}. In the case of problems with footnotes, it may
be possible to correct the situation using commands
\texttt{\textbackslash{}footnotemark} and
\texttt{\textbackslash{}footnotetext}.

\[\begin{aligned}
(x+y)^3&=(x+y)(x+y)^2\\
       &=(x+y)(x^2+2xy+y^2) \label{eqn:example} \\
       &=x^3+3x^2y+3xy^3+x^3.
\end{aligned}\]

\hypertarget{supporting-information-si}{%
\subsection*{Supporting Information
(SI)}\label{supporting-information-si}}
\addcontentsline{toc}{subsection}{Supporting Information (SI)}

The main text of the paper must stand on its own without the SI. Refer
to SI in the manuscript at an appropriate point in the text. Number
supporting figures and tables starting with S1, S2, etc. Authors are
limited to no more than 10 SI files, not including movie files. Authors
who place detailed materials and methods in SI must provide sufficient
detail in the main text methods to enable a reader to follow the logic
of the procedures and results and also must reference the online
methods. If a paper is fundamentally a study of a new method or
technique, then the methods must be described completely in the main
text. Because PNAS edits SI and composes it into a single PDF, authors
must provide the following file formats only.

\hypertarget{si-text}{%
\subsubsection*{SI Text}\label{si-text}}
\addcontentsline{toc}{subsubsection}{SI Text}

Supply Word, RTF, or LaTeX files (LaTeX files must be accompanied by a
PDF with the same file name for visual reference).

\hypertarget{si-figures}{%
\subsubsection*{SI Figures}\label{si-figures}}
\addcontentsline{toc}{subsubsection}{SI Figures}

Provide a brief legend for each supporting figure after the supporting
text. Provide figure images in TIFF, EPS, high-resolution PDF, JPEG, or
GIF format; figures may not be embedded in manuscript text. When saving
TIFF files, use only LZW compression; do not use JPEG compression. Do
not save figure numbers, legends, or author names as part of the image.
Composite figures must be pre-assembled.

\hypertarget{d-figures}{%
\subsubsection*{3D Figures}\label{d-figures}}
\addcontentsline{toc}{subsubsection}{3D Figures}

Supply a composable U3D or PRC file so that it may be edited and
composed. Authors may submit a PDF file but please note it will be
published in raw format and will not be edited or composed.

\hypertarget{si-tables}{%
\subsubsection*{SI Tables}\label{si-tables}}
\addcontentsline{toc}{subsubsection}{SI Tables}

Supply Word, RTF, or LaTeX files (LaTeX files must be accompanied by a
PDF with the same file name for visual reference); include only one
table per file. Do not use tabs or spaces to separate columns in Word
tables.

\hypertarget{si-datasets}{%
\subsubsection*{SI Datasets}\label{si-datasets}}
\addcontentsline{toc}{subsubsection}{SI Datasets}

Supply Excel (.xls), RTF, or PDF files. This file type will be published
in raw format and will not be edited or composed.

\hypertarget{si-movies}{%
\subsubsection*{SI Movies}\label{si-movies}}
\addcontentsline{toc}{subsubsection}{SI Movies}

Supply Audio Video Interleave (avi), Quicktime (mov), Windows Media
(wmv), animated GIF (gif), or MPEG files and submit a brief legend for
each movie in a Word or RTF file. All movies should be submitted at the
desired reproduction size and length. Movies should be no more than 10
MB in size.

\hypertarget{still-images}{%
\subsubsection*{Still images}\label{still-images}}
\addcontentsline{toc}{subsubsection}{Still images}

Authors must provide a still image from each video file. Supply TIFF,
EPS, high-resolution PDF, JPEG, or GIF files.

\hypertarget{appendices}{%
\subsubsection*{Appendices}\label{appendices}}
\addcontentsline{toc}{subsubsection}{Appendices}

PNAS prefers that authors submit individual source files to ensure
readability. If this is not possible, supply a single PDF file that
contains all of the SI associated with the paper. This file type will be
published in raw format and will not be edited or composed.

\showmatmethods
\showacknow
\pnasbreak

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-belkin2002using}{}%
1. Belkin M, Niyogi P (2002) Using manifold stucture for partially
labeled classification. \emph{Advances in Neural Information Processing
Systems}, pp 929--936.

\leavevmode\hypertarget{ref-berard1994embedding}{}%
2. Bérard P, Besson G, Gallot S (1994) Embedding riemannian manifolds by
their heat kernel. \emph{Geometric \& Functional Analysis GAFA}
4(4):373--398.

\leavevmode\hypertarget{ref-coifman2005geometric}{}%
3. Coifman RR, et al. (2005) Geometric diffusions as a tool for harmonic
analysis and structure definition of data: Diffusion maps.
\emph{Proceedings of the National Academy of Sciences of the United
States of America} 102(21):7426--7431.



% Bibliography
% \bibliography{pnas-sample}

\end{document}

