install.packages("devtools")
install.packages("ggplot2")
install.packages("bit")
install.packages("ff")
install.packages("ffbase")
install.packages("rJava")
install.packages("snow")
install.packages("XML")
install.packages("jsonlite")
install.packages("codetools")
install.packages("formatR")
install.packages("RJSONIO")
install.packages("httr")
install.packages("mailR")
install.packages("DBI")
install.packages("urltools")
install.packages("plyr")
install.packages("grid")
install.packages("gridExtra")
devtools::install_github("ohdsi/Cyclops", dep = TRUE)
devtools::install_github("ohdsi/SqlRender", dep = FALSE)
devtools::install_github("ohdsi/ParallelLogger", dep = FALSE)
devtools::install_github("ohdsi/OhdsiRTools", dep = FALSE)
devtools::install_github("ohdsi/DatabaseConnector", ref = "develop", dep = FALSE)
devtools::install_github("ohdsi/FeatureExtraction", dep = FALSE)
devtools::install_github("ohdsi/CohortMethod", ref = "develop", dep = FALSE)
devtools::install_github("ohdsi/MethodEvaluation", ref = "develop", dep = FALSE)


